function my_imshow(im, noise, denoised)
figure('Name',"Denoise",'NumberTitle','off')
subplot(1,3,1)
imshow(uint8(im))
title("im")
subplot(1,3,2)
imshow(uint8(noise))
title("noise")
subplot(1,3,3)
imshow(uint8(denoised))
title("denoised")
end